from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ErrorReason(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ERROR_REASON_UNSPECIFIED: _ClassVar[ErrorReason]
    ERROR_REASON_SCHEMA_PARSE_ERROR: _ClassVar[ErrorReason]
    ERROR_REASON_SCHEMA_TYPE_ERROR: _ClassVar[ErrorReason]
    ERROR_REASON_UNKNOWN_DEFINITION: _ClassVar[ErrorReason]
    ERROR_REASON_UNKNOWN_RELATION_OR_PERMISSION: _ClassVar[ErrorReason]
    ERROR_REASON_TOO_MANY_UPDATES_IN_REQUEST: _ClassVar[ErrorReason]
    ERROR_REASON_TOO_MANY_PRECONDITIONS_IN_REQUEST: _ClassVar[ErrorReason]
    ERROR_REASON_WRITE_OR_DELETE_PRECONDITION_FAILURE: _ClassVar[ErrorReason]
    ERROR_REASON_SERVICE_READ_ONLY: _ClassVar[ErrorReason]
    ERROR_REASON_UNKNOWN_CAVEAT: _ClassVar[ErrorReason]
    ERROR_REASON_INVALID_SUBJECT_TYPE: _ClassVar[ErrorReason]
    ERROR_REASON_CAVEAT_PARAMETER_TYPE_ERROR: _ClassVar[ErrorReason]
    ERROR_REASON_UPDATES_ON_SAME_RELATIONSHIP: _ClassVar[ErrorReason]
    ERROR_REASON_CANNOT_UPDATE_PERMISSION: _ClassVar[ErrorReason]
    ERROR_REASON_CAVEAT_EVALUATION_ERROR: _ClassVar[ErrorReason]
    ERROR_REASON_INVALID_CURSOR: _ClassVar[ErrorReason]
    ERROR_REASON_TOO_MANY_RELATIONSHIPS_FOR_TRANSACTIONAL_DELETE: _ClassVar[ErrorReason]
    ERROR_REASON_MAX_RELATIONSHIP_CONTEXT_SIZE: _ClassVar[ErrorReason]
    ERROR_REASON_ATTEMPT_TO_RECREATE_RELATIONSHIP: _ClassVar[ErrorReason]
    ERROR_REASON_MAXIMUM_DEPTH_EXCEEDED: _ClassVar[ErrorReason]
    ERROR_REASON_SERIALIZATION_FAILURE: _ClassVar[ErrorReason]
    ERROR_REASON_TOO_MANY_CHECKS_IN_REQUEST: _ClassVar[ErrorReason]
    ERROR_REASON_EXCEEDS_MAXIMUM_ALLOWABLE_LIMIT: _ClassVar[ErrorReason]
    ERROR_REASON_INVALID_FILTER: _ClassVar[ErrorReason]
    ERROR_REASON_INMEMORY_TOO_MANY_CONCURRENT_UPDATES: _ClassVar[ErrorReason]
    ERROR_REASON_EMPTY_PRECONDITION: _ClassVar[ErrorReason]
    ERROR_REASON_COUNTER_ALREADY_REGISTERED: _ClassVar[ErrorReason]
    ERROR_REASON_COUNTER_NOT_REGISTERED: _ClassVar[ErrorReason]
    ERROR_REASON_WILDCARD_NOT_ALLOWED: _ClassVar[ErrorReason]
ERROR_REASON_UNSPECIFIED: ErrorReason
ERROR_REASON_SCHEMA_PARSE_ERROR: ErrorReason
ERROR_REASON_SCHEMA_TYPE_ERROR: ErrorReason
ERROR_REASON_UNKNOWN_DEFINITION: ErrorReason
ERROR_REASON_UNKNOWN_RELATION_OR_PERMISSION: ErrorReason
ERROR_REASON_TOO_MANY_UPDATES_IN_REQUEST: ErrorReason
ERROR_REASON_TOO_MANY_PRECONDITIONS_IN_REQUEST: ErrorReason
ERROR_REASON_WRITE_OR_DELETE_PRECONDITION_FAILURE: ErrorReason
ERROR_REASON_SERVICE_READ_ONLY: ErrorReason
ERROR_REASON_UNKNOWN_CAVEAT: ErrorReason
ERROR_REASON_INVALID_SUBJECT_TYPE: ErrorReason
ERROR_REASON_CAVEAT_PARAMETER_TYPE_ERROR: ErrorReason
ERROR_REASON_UPDATES_ON_SAME_RELATIONSHIP: ErrorReason
ERROR_REASON_CANNOT_UPDATE_PERMISSION: ErrorReason
ERROR_REASON_CAVEAT_EVALUATION_ERROR: ErrorReason
ERROR_REASON_INVALID_CURSOR: ErrorReason
ERROR_REASON_TOO_MANY_RELATIONSHIPS_FOR_TRANSACTIONAL_DELETE: ErrorReason
ERROR_REASON_MAX_RELATIONSHIP_CONTEXT_SIZE: ErrorReason
ERROR_REASON_ATTEMPT_TO_RECREATE_RELATIONSHIP: ErrorReason
ERROR_REASON_MAXIMUM_DEPTH_EXCEEDED: ErrorReason
ERROR_REASON_SERIALIZATION_FAILURE: ErrorReason
ERROR_REASON_TOO_MANY_CHECKS_IN_REQUEST: ErrorReason
ERROR_REASON_EXCEEDS_MAXIMUM_ALLOWABLE_LIMIT: ErrorReason
ERROR_REASON_INVALID_FILTER: ErrorReason
ERROR_REASON_INMEMORY_TOO_MANY_CONCURRENT_UPDATES: ErrorReason
ERROR_REASON_EMPTY_PRECONDITION: ErrorReason
ERROR_REASON_COUNTER_ALREADY_REGISTERED: ErrorReason
ERROR_REASON_COUNTER_NOT_REGISTERED: ErrorReason
ERROR_REASON_WILDCARD_NOT_ALLOWED: ErrorReason
