---
repos:
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    # Ruff version.
    rev: "v0.6.1"
    hooks:
      # Run the linter.
      - id: "ruff"
        exclude: ".*_pb2.*"
      # Run the formatter.
      - id: "ruff-format"
        exclude: ".*_pb2.*"
  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.35.1"
    hooks:
      - id: "yamllint"
  - repo: "https://github.com/RobertCraigie/pyright-python"
    rev: "v1.1.376"
    hooks:
      - id: "pyright"
        args: ["--verbose"]
