"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .developer_pb2 import *
class DeveloperServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    EditCheck:grpc.UnaryUnaryMultiCallable[
        global___EditCheckRequest,
        global___EditCheckResponse] = ...

    Validate:grpc.UnaryUnaryMultiCallable[
        global___ValidateRequest,
        global___ValidateResponse] = ...

    Share:grpc.UnaryUnaryMultiCallable[
        global___ShareRequest,
        global___ShareResponse] = ...

    LookupShared:grpc.UnaryUnaryMultiCallable[
        global___LookupShareRequest,
        global___LookupShareResponse] = ...

    UpgradeSchema:grpc.UnaryUnaryMultiCallable[
        global___UpgradeSchemaRequest,
        global___UpgradeSchemaResponse] = ...

    FormatSchema:grpc.UnaryUnaryMultiCallable[
        global___FormatSchemaRequest,
        global___FormatSchemaResponse] = ...


class DeveloperServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def EditCheck(self,
        request: global___EditCheckRequest,
        context: grpc.ServicerContext,
    ) -> global___EditCheckResponse: ...

    @abc.abstractmethod
    def Validate(self,
        request: global___ValidateRequest,
        context: grpc.ServicerContext,
    ) -> global___ValidateResponse: ...

    @abc.abstractmethod
    def Share(self,
        request: global___ShareRequest,
        context: grpc.ServicerContext,
    ) -> global___ShareResponse: ...

    @abc.abstractmethod
    def LookupShared(self,
        request: global___LookupShareRequest,
        context: grpc.ServicerContext,
    ) -> global___LookupShareResponse: ...

    @abc.abstractmethod
    def UpgradeSchema(self,
        request: global___UpgradeSchemaRequest,
        context: grpc.ServicerContext,
    ) -> global___UpgradeSchemaResponse: ...

    @abc.abstractmethod
    def FormatSchema(self,
        request: global___FormatSchemaRequest,
        context: grpc.ServicerContext,
    ) -> global___FormatSchemaResponse: ...


def add_DeveloperServiceServicer_to_server(servicer: DeveloperServiceServicer, server: grpc.Server) -> None: ...
