"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from authzed.api.v0.core_pb2 import (
    RelationReference as authzed___api___v0___core_pb2___RelationReference,
)

from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Metadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def metadata_message(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___any_pb2___Any]: ...

    def __init__(self,
        *,
        metadata_message : typing___Optional[typing___Iterable[google___protobuf___any_pb2___Any]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"metadata_message",b"metadata_message"]) -> None: ...
type___Metadata = Metadata

class NamespaceDefinition(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    @property
    def relation(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Relation]: ...

    @property
    def metadata(self) -> type___Metadata: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        relation : typing___Optional[typing___Iterable[type___Relation]] = None,
        metadata : typing___Optional[type___Metadata] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata",u"name",b"name",u"relation",b"relation"]) -> None: ...
type___NamespaceDefinition = NamespaceDefinition

class Relation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    @property
    def userset_rewrite(self) -> type___UsersetRewrite: ...

    @property
    def type_information(self) -> type___TypeInformation: ...

    @property
    def metadata(self) -> type___Metadata: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        userset_rewrite : typing___Optional[type___UsersetRewrite] = None,
        type_information : typing___Optional[type___TypeInformation] = None,
        metadata : typing___Optional[type___Metadata] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata",u"type_information",b"type_information",u"userset_rewrite",b"userset_rewrite"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata",u"name",b"name",u"type_information",b"type_information",u"userset_rewrite",b"userset_rewrite"]) -> None: ...
type___Relation = Relation

class TypeInformation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def allowed_direct_relations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[authzed___api___v0___core_pb2___RelationReference]: ...

    def __init__(self,
        *,
        allowed_direct_relations : typing___Optional[typing___Iterable[authzed___api___v0___core_pb2___RelationReference]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"allowed_direct_relations",b"allowed_direct_relations"]) -> None: ...
type___TypeInformation = TypeInformation

class UsersetRewrite(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def union(self) -> type___SetOperation: ...

    @property
    def intersection(self) -> type___SetOperation: ...

    @property
    def exclusion(self) -> type___SetOperation: ...

    def __init__(self,
        *,
        union : typing___Optional[type___SetOperation] = None,
        intersection : typing___Optional[type___SetOperation] = None,
        exclusion : typing___Optional[type___SetOperation] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"exclusion",b"exclusion",u"intersection",b"intersection",u"rewrite_operation",b"rewrite_operation",u"union",b"union"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"exclusion",b"exclusion",u"intersection",b"intersection",u"rewrite_operation",b"rewrite_operation",u"union",b"union"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"rewrite_operation",b"rewrite_operation"]) -> typing_extensions___Literal["union","intersection","exclusion"]: ...
type___UsersetRewrite = UsersetRewrite

class SetOperation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Child(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class This(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

            def __init__(self,
                ) -> None: ...
        type___This = This


        @property
        def _this(self) -> type___SetOperation.Child.This: ...

        @property
        def computed_userset(self) -> type___ComputedUserset: ...

        @property
        def tuple_to_userset(self) -> type___TupleToUserset: ...

        @property
        def userset_rewrite(self) -> type___UsersetRewrite: ...

        def __init__(self,
            *,
            _this : typing___Optional[type___SetOperation.Child.This] = None,
            computed_userset : typing___Optional[type___ComputedUserset] = None,
            tuple_to_userset : typing___Optional[type___TupleToUserset] = None,
            userset_rewrite : typing___Optional[type___UsersetRewrite] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"_this",b"_this",u"child_type",b"child_type",u"computed_userset",b"computed_userset",u"tuple_to_userset",b"tuple_to_userset",u"userset_rewrite",b"userset_rewrite"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"_this",b"_this",u"child_type",b"child_type",u"computed_userset",b"computed_userset",u"tuple_to_userset",b"tuple_to_userset",u"userset_rewrite",b"userset_rewrite"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions___Literal[u"child_type",b"child_type"]) -> typing_extensions___Literal["_this","computed_userset","tuple_to_userset","userset_rewrite"]: ...
    type___Child = Child


    @property
    def child(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___SetOperation.Child]: ...

    def __init__(self,
        *,
        child : typing___Optional[typing___Iterable[type___SetOperation.Child]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"child",b"child"]) -> None: ...
type___SetOperation = SetOperation

class TupleToUserset(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Tupleset(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        relation: typing___Text = ...

        def __init__(self,
            *,
            relation : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"relation",b"relation"]) -> None: ...
    type___Tupleset = Tupleset


    @property
    def tupleset(self) -> type___TupleToUserset.Tupleset: ...

    @property
    def computed_userset(self) -> type___ComputedUserset: ...

    def __init__(self,
        *,
        tupleset : typing___Optional[type___TupleToUserset.Tupleset] = None,
        computed_userset : typing___Optional[type___ComputedUserset] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"computed_userset",b"computed_userset",u"tupleset",b"tupleset"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"computed_userset",b"computed_userset",u"tupleset",b"tupleset"]) -> None: ...
type___TupleToUserset = TupleToUserset

class ComputedUserset(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ObjectValue = typing___NewType('ObjectValue', builtin___int)
    type___ObjectValue = ObjectValue
    Object: _Object
    class _Object(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ComputedUserset.ObjectValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        TUPLE_OBJECT = typing___cast(ComputedUserset.ObjectValue, 0)
        TUPLE_USERSET_OBJECT = typing___cast(ComputedUserset.ObjectValue, 1)
    TUPLE_OBJECT = typing___cast(ComputedUserset.ObjectValue, 0)
    TUPLE_USERSET_OBJECT = typing___cast(ComputedUserset.ObjectValue, 1)

    object: type___ComputedUserset.ObjectValue = ...
    relation: typing___Text = ...

    def __init__(self,
        *,
        object : typing___Optional[type___ComputedUserset.ObjectValue] = None,
        relation : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"object",b"object",u"relation",b"relation"]) -> None: ...
type___ComputedUserset = ComputedUserset
