"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Metadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def metadata_message(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]: ...
    def __init__(
        self,
        *,
        metadata_message: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata_message", b"metadata_message"]) -> None: ...

global___Metadata = Metadata

class NamespaceDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def relation(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Relation]: ...
    @property
    def metadata(self) -> global___Metadata: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        relation: collections.abc.Iterable[global___Relation] | None = ...,
        metadata: global___Metadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata", b"metadata", "name", b"name", "relation", b"relation"]) -> None: ...

global___NamespaceDefinition = NamespaceDefinition

class Relation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    USERSET_REWRITE_FIELD_NUMBER: builtins.int
    TYPE_INFORMATION_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def userset_rewrite(self) -> global___UsersetRewrite: ...
    @property
    def type_information(self) -> global___TypeInformation: ...
    @property
    def metadata(self) -> global___Metadata: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        userset_rewrite: global___UsersetRewrite | None = ...,
        type_information: global___TypeInformation | None = ...,
        metadata: global___Metadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metadata", b"metadata", "type_information", b"type_information", "userset_rewrite", b"userset_rewrite"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata", b"metadata", "name", b"name", "type_information", b"type_information", "userset_rewrite", b"userset_rewrite"]) -> None: ...

global___Relation = Relation

class TypeInformation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOWED_DIRECT_RELATIONS_FIELD_NUMBER: builtins.int
    @property
    def allowed_direct_relations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AllowedRelation]: ...
    def __init__(
        self,
        *,
        allowed_direct_relations: collections.abc.Iterable[global___AllowedRelation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["allowed_direct_relations", b"allowed_direct_relations"]) -> None: ...

global___TypeInformation = TypeInformation

class AllowedRelation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class PublicWildcard(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    NAMESPACE_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    PUBLIC_WILDCARD_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    relation: builtins.str
    @property
    def public_wildcard(self) -> global___AllowedRelation.PublicWildcard: ...
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        relation: builtins.str = ...,
        public_wildcard: global___AllowedRelation.PublicWildcard | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["public_wildcard", b"public_wildcard", "relation", b"relation", "relation_or_wildcard", b"relation_or_wildcard"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["namespace", b"namespace", "public_wildcard", b"public_wildcard", "relation", b"relation", "relation_or_wildcard", b"relation_or_wildcard"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["relation_or_wildcard", b"relation_or_wildcard"]) -> typing_extensions.Literal["relation", "public_wildcard"] | None: ...

global___AllowedRelation = AllowedRelation

class UsersetRewrite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNION_FIELD_NUMBER: builtins.int
    INTERSECTION_FIELD_NUMBER: builtins.int
    EXCLUSION_FIELD_NUMBER: builtins.int
    @property
    def union(self) -> global___SetOperation: ...
    @property
    def intersection(self) -> global___SetOperation: ...
    @property
    def exclusion(self) -> global___SetOperation: ...
    def __init__(
        self,
        *,
        union: global___SetOperation | None = ...,
        intersection: global___SetOperation | None = ...,
        exclusion: global___SetOperation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["exclusion", b"exclusion", "intersection", b"intersection", "rewrite_operation", b"rewrite_operation", "union", b"union"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["exclusion", b"exclusion", "intersection", b"intersection", "rewrite_operation", b"rewrite_operation", "union", b"union"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["rewrite_operation", b"rewrite_operation"]) -> typing_extensions.Literal["union", "intersection", "exclusion"] | None: ...

global___UsersetRewrite = UsersetRewrite

class SetOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Child(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class This(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            def __init__(
                self,
            ) -> None: ...

        _THIS_FIELD_NUMBER: builtins.int
        COMPUTED_USERSET_FIELD_NUMBER: builtins.int
        TUPLE_TO_USERSET_FIELD_NUMBER: builtins.int
        USERSET_REWRITE_FIELD_NUMBER: builtins.int
        @property
        def _this(self) -> global___SetOperation.Child.This: ...
        @property
        def computed_userset(self) -> global___ComputedUserset: ...
        @property
        def tuple_to_userset(self) -> global___TupleToUserset: ...
        @property
        def userset_rewrite(self) -> global___UsersetRewrite: ...
        def __init__(
            self,
            *,
            _this: global___SetOperation.Child.This | None = ...,
            computed_userset: global___ComputedUserset | None = ...,
            tuple_to_userset: global___TupleToUserset | None = ...,
            userset_rewrite: global___UsersetRewrite | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_this", b"_this", "child_type", b"child_type", "computed_userset", b"computed_userset", "tuple_to_userset", b"tuple_to_userset", "userset_rewrite", b"userset_rewrite"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_this", b"_this", "child_type", b"child_type", "computed_userset", b"computed_userset", "tuple_to_userset", b"tuple_to_userset", "userset_rewrite", b"userset_rewrite"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["child_type", b"child_type"]) -> typing_extensions.Literal["_this", "computed_userset", "tuple_to_userset", "userset_rewrite"] | None: ...

    CHILD_FIELD_NUMBER: builtins.int
    @property
    def child(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SetOperation.Child]: ...
    def __init__(
        self,
        *,
        child: collections.abc.Iterable[global___SetOperation.Child] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["child", b"child"]) -> None: ...

global___SetOperation = SetOperation

class TupleToUserset(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Tupleset(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RELATION_FIELD_NUMBER: builtins.int
        relation: builtins.str
        def __init__(
            self,
            *,
            relation: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["relation", b"relation"]) -> None: ...

    TUPLESET_FIELD_NUMBER: builtins.int
    COMPUTED_USERSET_FIELD_NUMBER: builtins.int
    @property
    def tupleset(self) -> global___TupleToUserset.Tupleset: ...
    @property
    def computed_userset(self) -> global___ComputedUserset: ...
    def __init__(
        self,
        *,
        tupleset: global___TupleToUserset.Tupleset | None = ...,
        computed_userset: global___ComputedUserset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["computed_userset", b"computed_userset", "tupleset", b"tupleset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["computed_userset", b"computed_userset", "tupleset", b"tupleset"]) -> None: ...

global___TupleToUserset = TupleToUserset

class ComputedUserset(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Object:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ObjectEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ComputedUserset._Object.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TUPLE_OBJECT: ComputedUserset._Object.ValueType  # 0
        TUPLE_USERSET_OBJECT: ComputedUserset._Object.ValueType  # 1

    class Object(_Object, metaclass=_ObjectEnumTypeWrapper): ...
    TUPLE_OBJECT: ComputedUserset.Object.ValueType  # 0
    TUPLE_USERSET_OBJECT: ComputedUserset.Object.ValueType  # 1

    OBJECT_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    object: global___ComputedUserset.Object.ValueType
    relation: builtins.str
    def __init__(
        self,
        *,
        object: global___ComputedUserset.Object.ValueType = ...,
        relation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["object", b"object", "relation", b"relation"]) -> None: ...

global___ComputedUserset = ComputedUserset
