# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from authzed.api.v0 import namespace_service_pb2 as authzed_dot_api_dot_v0_dot_namespace__service__pb2


class NamespaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadConfig = channel.unary_unary(
                '/authzed.api.v0.NamespaceService/ReadConfig',
                request_serializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.ReadConfigRequest.SerializeToString,
                response_deserializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.ReadConfigResponse.FromString,
                )
        self.WriteConfig = channel.unary_unary(
                '/authzed.api.v0.NamespaceService/WriteConfig',
                request_serializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.WriteConfigRequest.SerializeToString,
                response_deserializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.WriteConfigResponse.FromString,
                )
        self.DeleteConfigs = channel.unary_unary(
                '/authzed.api.v0.NamespaceService/DeleteConfigs',
                request_serializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.DeleteConfigsRequest.SerializeToString,
                response_deserializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.DeleteConfigsResponse.FromString,
                )


class NamespaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamespaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadConfig,
                    request_deserializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.ReadConfigRequest.FromString,
                    response_serializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.ReadConfigResponse.SerializeToString,
            ),
            'WriteConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteConfig,
                    request_deserializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.WriteConfigRequest.FromString,
                    response_serializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.WriteConfigResponse.SerializeToString,
            ),
            'DeleteConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConfigs,
                    request_deserializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.DeleteConfigsRequest.FromString,
                    response_serializer=authzed_dot_api_dot_v0_dot_namespace__service__pb2.DeleteConfigsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authzed.api.v0.NamespaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NamespaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authzed.api.v0.NamespaceService/ReadConfig',
            authzed_dot_api_dot_v0_dot_namespace__service__pb2.ReadConfigRequest.SerializeToString,
            authzed_dot_api_dot_v0_dot_namespace__service__pb2.ReadConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authzed.api.v0.NamespaceService/WriteConfig',
            authzed_dot_api_dot_v0_dot_namespace__service__pb2.WriteConfigRequest.SerializeToString,
            authzed_dot_api_dot_v0_dot_namespace__service__pb2.WriteConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authzed.api.v0.NamespaceService/DeleteConfigs',
            authzed_dot_api_dot_v0_dot_namespace__service__pb2.DeleteConfigsRequest.SerializeToString,
            authzed_dot_api_dot_v0_dot_namespace__service__pb2.DeleteConfigsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
