---
name: "Publish to PyPI"
on:  # yamllint disable-line rule:truthy
  release:
    types:
      - "published"
jobs:
  publish:
    name: "Build & Publish"
    runs-on: "ubuntu-latest"
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: "pypi"
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: "write"
    steps:
      - uses: "actions/checkout@v5"
      - uses: "astral-sh/setup-uv@v7"
      # This gives us a version number without the release prefix
      - name: "Write release version"
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: "Set the release number in pyproject.toml"
        run: "uv version $VERSION"
      - name: "Build wheel and source tarball"
        run: "uv build"
      - name: "Publish"
        uses: "pypa/gh-action-pypi-publish@release/v1"
