---
name: "Publish to PyPI"
on: "push"
jobs:
  publish:
    name: "Build & Publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.6"
      - name: "Install pypa/build"
        run: "python -m pip install build --user"
      - name: "Build wheel and source tarball"
        run: "python -m build --sdist --wheel --outdir dist/ ."
      - name: "Publish"
        if: "startsWith(github.ref, 'refs/tags')"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
